### ISSUE TITLE
The reg_f3d GPU capability has been de-activated in the current release

### ISSUE THREAD

**Issue by volcanofly** [SuperElastix/niftyreg#1]
Hi,

I checked the .cpp file and found that as long as the user specifies "-gpu", it prints "The reg_f3d GPU capability has been de-activated in the current release" and exit.
I was wondering if it means that GPU acceleration is not available for current release. If so, which release enables GPU acceleration?
Thank you so much!

**Comment by wentaozhu** [comment]
It seems the niftyreg has no one to support now. I found the same situation in the official one: https://github.com/KCL-BMEIS/niftyreg/issues

**Comment by FBerendsen** [comment]
This repo is a(n outdated) mirror.
